import matplotlib.pyplot as plt


concepts_singletons = [
    (10, ['the world', 'the weather', 'the person', 'the descendants', 'the turtle', 'the snail', 'the whale', 'the prawns or shrimp', 'the squirrel', 'the opossum', 'the hare', 'the shell', 'the stable or stall', 'the foal or colt', 'the fever', 'to be born', 'the pot', 'the mill', 'the dough', 'the collar', 'the chimney', 'the mortar(2)', 'the ladder', 'the trough', 'the fence', 'the sweet potato', 'the lasso', 'the plant', 'the millet or sorghum', 'the sugar cane', 'the adze', 'the statue', 'the axle', 'the raft', 'the paddle', 'to drive', 'the sail', 'to preserve', 'the debt', 'rich', 'to rescue', 'always', 'the dawn', 'blue', 'the blame', 'the danger', 'to learn', 'to admit', 'the drum', 'the queen', 'the attack', 'the spear', 'the adultery', 'innocent', 'the rape', 'the idol']),
    (21, ['the kettle', 'the pepper', 'the dish', 'the cheese', 'the lamp or torch', 'the pipe', 'the paint', 'the glass', 'the chain', 'the cart or wagon', 'the tax', 'Sunday', 'the gun', 'the address', 'the petroleum', 'the number', 'the electricity', 'the music', 'the train']),
    (11, ['the mainland', 'the ancestors', 'the wedding', 'the father', 'the grandfather', 'the monkey', 'the shark', 'the spider', 'the jaguar', 'the pig', 'the livestock', 'healthy', 'the womb', 'the stomach', 'the knife(1)', 'the vegetables', 'the milk', 'the veil', 'the fur', 'the razor', 'the floor', 'the arch', 'the latch or door-bolt', 'the beam', 'the wall', 'the post or pole', 'the camp', 'the pine', 'the vine', 'the fork(2)/pitchfork', 'the hoe', 'the rake', 'the tool', 'the port', 'the rudder', 'the canoe', 'the yoke', 'to pay', 'to count', 'the fault', 'stupid', 'secret', 'to understand', 'to try', 'certain', 'the pupil', 'the horn or trumpet', 'the speech', 'the slave', 'the guest', 'the village', 'the weapons', 'the captive or prisoner', 'the victory', 'the war or battle', 'the plaintiff', 'the magic', 'to pray']),
    (5, ['the wind', 'the river or stream', 'rough(2)', 'the shade or shadow', 'the sand', 'the cape', 'to freeze', 'the storm', 'the foam', 'the young woman', 'the parents-in-law', 'the husband', 'the niece', 'the older brother', 'the mother', 'the wasp', 'the cormorant', 'the vulture', 'the anteater', 'the nest', 'the crow', 'the sow', 'the beaver', 'the tick', 'to bathe', 'the blister', 'lazy', 'the body', 'deaf', 'to snore', 'the spine', 'the chest', 'the pubic hair', 'the pus', 'the wound or sore', 'lame', 'to spit', 'the belly', 'to beget', 'to kill', 'sick/ill', 'the flesh', 'the beard', 'to perspire', 'to choke', 'to roast or fry', 'the mortar(1)', 'to stir or to mix', 'to swallow', 'the grease or fat', 'to sew', 'the comb', 'the fireplace', 'the rafter', 'the ridgepole', 'the door or gate', 'the house', 'the garden-house', 'the forked branch', 'the bark', 'the branch', 'the sap', 'the hay', 'the fir', 'the threshing-floor', 'to split', 'to pull', 'to cast', 'to fan', 'the potter', 'the knot', 'to stab', 'to carve', 'to sink', 'to roll', 'to shake', 'to turn around', 'to crawl', 'to carry on shoulder', 'the outrigger', 'to arrive', 'to catch', 'to disappear', 'to go down', 'to splash', 'to lead', 'to give', 'to look for', 'the side', 'the edge', 'low', 'to shut', 'pointed', 'similar', 'the bottom', 'the north', 'five', 'one', 'empty', 'often', 'immediately', 'the end(2)', 'to be late', 'the midday', 'the morning', 'the summer', 'the day(1)', 'late', 'now', 'clean', 'rough(1)', 'white', 'to see', 'to sniff', 'the anxiety', 'right(2)', 'to hate', 'true', 'the anger', 'to choose', 'to love', 'to kiss', 'mad', 'to teach', 'to remember', 'to ask(2)', 'to ask(1)', 'to call(1)', 'to shriek', 'to speak or talk', 'the rattle', 'to liberate', 'the plot', 'the fish trap', 'the bait', 'to retreat', 'to miss', 'the helmet', 'the bow', 'to swear', 'same', 'without']),
    (16, ['the goose', 'the duck', 'the kangaroo', 'the bean', 'the hat or cap', 'the cloak', 'the board', 'the garden', 'the citrus fruit', 'the barley', 'the ship', 'the square', 'a hundred', 'the colour/color', 'the peace', 'the god', 'the mosque', 'the candy/sweets', 'the street']),
    (9, ['the lake', 'the sky', 'the cave', 'the lagoon', 'the earthquake', 'the widow', 'the young man', 'the orphan', 'the twins', "the mother's sister", 'the divorce', "the father's brother", 'the tapir', 'the chameleon', 'the mosquito', 'the termites', 'the lizard', 'the mare', 'the dandruff', 'strong', 'the collarbone', 'to blink', 'the kidney', 'the disease', 'the vulva', 'bald', 'the fruit', 'the breakfast', 'to dye', 'the bracelet', 'the bead', 'the cookhouse', 'the hammock', 'the grain', 'the palm tree', 'to plough/plow', 'the netbag', 'the mat', 'the fan', 'the sledge/sled', 'to row', 'to buy', 'the beggar', 'round', 'the hook', 'to change', 'to measure', 'the part', 'twenty', 'proud', 'the grief', 'to regret or be sorry', 'to think(1)', 'the intention', 'to explain', 'to deny', 'the voice', 'the word', 'to help', 'the fortress', 'the armour', 'the sling', 'the thief', 'to adjudicate', 'the perjury', 'the heaven', 'the fairy or elf', 'to curse']),
    (13, ['the island', 'the relatives', 'the cock/rooster', 'the stallion', 'the cow', 'the medicine', 'the corpse', 'the jug/pitcher', 'the tongs', 'the thread', 'the jewel', 'the ointment', 'the handkerchief or rag', 'the hut', 'the ditch', 'the sickle or scythe', 'to paint', 'the iron', 'the boomerang', 'to hire', 'the line', 'easy', 'the doubt', 'to believe', 'to promise', 'to command or order', 'the citizen', 'to condemn', 'the sacrifice', 'the license plate']),
    (12, ['the grandmother', 'the scorpion', 'the cattle', 'the frog', 'the porpoise or dolphin', 'the pasture', 'the dove', 'the bear', 'the bull', 'the lung', 'the grave', 'the fermented drink', 'the honey', 'the ornament or adornment', 'the poncho', 'the mason', 'the mushroom', 'the gourd', 'the blacksmith', 'the work', 'the glue', 'the chisel', 'the oar', 'the merchant', 'expensive', 'the age', 'to forgive', 'to suspect', 'the need or necessity', 'because', 'to betray', 'the flute', 'the friend', 'the servant', 'the prostitute', 'the master', 'to rule or govern', 'the judgment', 'the omen', 'holy']),
    (19, ['the saucer', 'the bowl', 'the gold', 'the nail', 'the boat', 'the coin', 'the wages', 'the cross', 'the custom', 'the army', 'the penalty or punishment', 'the witness']),
    (20, ['the crocodile or alligator', 'the mule', 'the oil', 'the potato', 'the pan', 'the button', 'the wheat', 'the bridge', 'the ball', 'zero', 'the court', 'the law', 'the temple', 'the screwdriver', 'the spectacles/glasses']),
    (6, ['the valley', 'the swamp', 'the spring or well', 'the arctic lights', 'the flame', 'calm', 'the mud', 'the dust', 'the cloud', 'the ice', 'the snow', 'the tide', 'the seagull', 'the worm', 'the beeswax', 'the elk/moose', 'the heron', 'the spider web', 'the ewe', 'the wolf', 'the eyebrow', 'the life', 'the shoulder', 'to cure', 'the beak', 'to rest', 'the nape of the neck', 'the penis', 'the wing', 'the throat', 'to hiccough', 'weak', 'the head', 'to breathe', 'the brain', 'the pestle', 'the food', 'the salt', 'the manioc bread', 'to cook', 'to bake', 'the belt', 'the shoemaker', 'the plait/braid', 'to tan', 'the cone', 'the seed', 'the oak', 'the whetstone', 'the anvil', 'to spread out', 'the rope', 'to pound', 'to mould/mold', 'to rub', 'the sculptor', 'to build', 'the broom', 'the path', 'the road', 'to turn', 'to kick', 'the mast', 'to owe', 'stingy', 'to earn', 'short', 'the end(1)', 'crooked', 'to divide', 'the top', 'the beginning', 'young', 'the day(2)', 'the afternoon', 'cold', 'dark', 'blunt', 'green', 'light(2)', 'surprised or astonished', 'ugly', 'clever', 'beautiful', 'the pity', 'the mistake', 'wrong', 'the deceit', 'difficult', 'no', 'and', 'to answer', 'the quarrel', 'to prevent', 'the native country', 'the host', 'the freeman', 'the fishhook', 'the fishing line', 'the booty', 'to steal', 'the arson', 'to worship', 'the ghost', 'the song']),
    (29, ['the camel', 'the table', 'the school', 'the bus', 'the bank', 'the radio', 'the plastic']),
    (23, ['the elephant', 'the donkey', 'the plate', 'the pocket', 'the banana', 'the shovel', 'the money', 'Wednesday', 'the week', 'the soldier', 'the religion', 'the government', 'the president', 'the injection', 'the calendar']),
    (26, ['the beer', 'the sock or stocking', 'the rice', 'the shop/store', 'Thursday', 'the church', 'the battery', 'the bomb']),
    (24, ['the horse', 'the boot', 'the towel', 'the brick', 'the candle', 'the market', 'a thousand', 'Friday', 'Monday', 'the book', 'the priest', 'the letter', 'the motorcycle', 'the airplane', 'the bicycle']),
    (17, ['the sea', 'the cat', 'the parrot', 'the sheep', 'the ox', 'the physician', 'the grape', 'the needle(1)', 'the shirt', 'the shoe', 'the pin', 'the tent', 'the lock', 'the padlock', 'the spade', 'the pumpkin or squash', 'the maize/corn', 'the carpenter', 'the saw', 'the scissors or shears', 'poor', 'the price', 'the bill', 'the teacher', 'to read', 'the town', 'the toilet', 'the election', 'the postcard', 'the tap/faucet', 'the nurse']),
    (25, ['the wine', 'the cup', 'the silk', 'Saturday', 'the pen', 'the hospital', 'the screw', 'the newspaper', 'the bottle', 'the tin/can', 'the minister', 'the cigarette', 'the post/mail']),
    (4, ['the light', 'the sun', 'the reef', 'the soil', 'the whirlpool', 'the fog', 'the mountain or hill', 'the smoke', 'the cousin', 'the child(1)', 'the sibling’s child', 'the old woman', 'the girl', 'the child(2)', 'the owl', 'the beehive', 'the quail', 'the mouse or rat', 'the bee', 'the jaw', 'to dream', 'the sinew or tendon', 'the wrist', 'the armpit', 'the goitre/goiter', 'the molar tooth', 'to vomit', 'the elbow', 'the thigh', 'the tail', 'to bury', 'the heel', 'the liver', 'to wake up', 'the feather', 'the waist', 'the navel', 'the intestines or guts', 'the nostril', 'the knee', 'the back', 'the buttocks', 'to scrape', 'the mead', 'to chew', 'raw', 'the drink', 'the leather', 'the loom', 'to live', 'the meeting house', 'the furrow', 'the tree stump', 'the larch', 'the paddy', 'to mow', 'to thresh', 'to break', 'to hang up', 'to cut', 'to forge', 'to pour', 'to squeeze', 'to tie', 'to wipe', 'to come back', 'to enter', 'to ride', 'to drip', 'to carry on head', 'to get', 'down', 'to remain', 'to sit', 'straight', 'shallow', 'to put', 'second', 'all', 'twice/two times', 'first', 'old', 'early', 'brackish', 'light(1)', 'dry', 'to pinch', 'to shine', 'bright', 'wet', 'wrinkled', 'sour', 'salty', 'warm', 'the fear', 'the pain', 'to embrace', 'to cry', 'if', 'to seem', 'to shout', 'to sing', 'to threaten', 'the name', 'to invite', 'to fight', 'to shoot', 'the battle-axe', 'other']),
    (33, ['the sugar', 'the police']),
    (32, ['the soap', 'the clock', 'the tea']),
    (7, ['the embers', 'the waterfall', 'to extinguish', 'the wave', 'the charcoal', 'the grandchild', 'the nephew', 'the uncle', 'the old man', "the mother's brother", 'the fowl', 'the gill', 'the snake', 'the coyote', 'the bat', 'the raccoon', 'the calf', 'the butterfly', 'the fish', 'the hen', 'the carcass', 'the footprint', 'to drown', 'tired', 'the vein or artery', 'the skull', 'the spleen', 'to yawn', 'the boil', 'the bunch', 'to knead', 'to sieve or to strain', 'to drink', 'to boil', 'the meat', 'the nut', 'the clothing or clothes', 'the necklace', 'the earring', 'the tattoo', 'the wool', 'the felt', 'the adobe', 'the yard or court', 'the harvest', 'the rye', 'the flower', 'the field', 'the grass', 'to smoke', 'to push', 'to wrap', 'to share', 'to own', 'to damage', 'the south', 'to join', 'left', 'more', 'two', 'the year', 'to finish', 'yellow', 'smooth', 'happy', 'greedy', 'to hope', 'to smile', 'the envy or jealousy', 'faithful', 'to dare', 'the manner', 'wise', 'the mind', 'clear', 'to imitate', 'to think(2)', 'to announce', 'to tell', 'to whisper', 'the neighbour', 'the chieftain', 'to defend', 'the ambush', 'the fishnet', 'to surrender', 'the shield', 'the trap', 'to acquit', 'the oath', 'the sorcerer or witch']),
    (8, ['the plain', 'the rainbow', 'the land', 'the dew', 'the bay', 'the steam', 'the rain', 'the widower', 'the baby', 'the grandparents', 'the aunt', "the father's sister", 'to marry', 'the boar', 'the scale', 'the herdsman', 'the grasshopper', 'the eagle', 'the centipede', 'the reindeer/caribou', 'the toucan', 'the hawk', 'the dog', 'the fox', 'the ram', 'the lamb', 'the cold', 'the horn', 'the palm of the hand', 'the face', 'the scar', 'the vagina', 'the shoulderblade', 'rotten', 'the famine', 'the lunch', 'the tailor', 'the glove', 'the ring', 'the headband or headdress', 'the awl', 'the pillow', 'the doorpost', 'the banyan', 'to plant', 'the yam', 'to press', 'the peg', 'to move', 'to crouch', 'to dance', 'to land', 'to sell', 'the thing', 'to trade or barter', 'to pile up', 'flat', 'the circle', 'the place', 'enough', 'ten', 'the crowd', 'ready', 'to hurry', 'the sound or noise', 'to taste', 'the bad luck', 'the praise', 'to want', 'the poet', 'to refuse', 'to forbid', 'to permit', 'the walking stick', 'the noble', 'the arrow', 'the defeat', 'the fisherman', 'the defendant', 'to accuse', 'to convict']),
    (22, ['the bread', 'the olive', 'the skirt', 'the coat', 'the trousers', 'Tuesday', 'the postage stamp', 'the mattress', 'the pill or tablet']),
    (18, ['the ocean', 'the animal', 'the rabbit', 'the goat', 'the fig', 'the oven', 'the soup', 'the fork', 'the flour', 'the cotton', 'the brush', 'the blanket', 'the key', 'the chair', 'the window', 'the coconut', 'the tin or tinplate', 'the silver', 'the copper', 'the lead', 'the time', 'to study', 'the tower', 'the fine', 'the judge', 'the prison', 'to preach', 'the altar']),
    (14, ['the savanna', 'the insect', 'the poison', 'the sausage', 'the mirror', 'the cloth', 'the linen', 'the shelf', 'the cassava/manioc', 'the oats', 'the anchor', 'the wheel', 'to weigh', 'the season', 'or', 'the idea', 'the cause', 'to write', 'the enemy', 'the country', 'the people', 'the clan', 'the club', 'the guard', 'guilty', 'the hell', 'the circumcision', 'to fast', 'the workshop', 'the birth certificate', "the driver's license", 'the sink', 'the crime']),
    (3, ['the shore', 'the firewood', 'the woman', 'the younger sibling', 'the sister', 'they', 'the daughter', 'the married man', 'the boy', 'the son', 'the wife', 'the fin', 'the stingray', 'the bird', 'the fly', 'the nit', 'the sandfly or midge or gnat', 'the ant', 'the forehead', 'the udder', 'the nasal mucus', 'blind', 'the breast', 'the earlobe', 'to have sex', 'the calf of the leg', 'to piss', 'the temples', 'the testicles', 'the chin', 'the tooth', 'the hip', 'the swelling', 'the heart', 'naked', 'to scratch', 'the rib', 'the skin or hide', 'to be alive', 'the eyelash', 'the eye', 'the eyelid', 'to shit', 'ripe', 'the egg', 'to be thirsty', 'to milk', 'the yolk', 'unripe', 'the spindle', 'to put on', 'the grass-skirt', 'the thatch', 'to cultivate', 'to dig', 'the tree trunk', 'the acorn', 'the birch', 'the needle(2)', 'the leaf', 'to sow', 'the nettle', 'to bend', 'to stretch', 'to cut down', 'broken', 'to carry', 'to go up', 'to leave', 'to fall', 'to dive', 'to keep', 'to give back', 'to gather', 'outside', 'to pick up', 'above', 'the fathom', 'to grow', 'big', 'thin', 'the piece', 'the half', 'few', 'only', 'third', 'the night', 'to last', 'fast', 'never', 'to begin', 'the evening', 'slow', 'dirty', 'to touch', 'black', 'to smell(2)', 'heavy', 'hard', 'hot', 'loud', 'soft', 'to feel', 'red', 'the tear', 'the shame', 'to laugh', 'bad', 'obscure', 'to forget', 'yes', 'to scold', 'to mumble', 'to obey', 'to meet', 'to become', 'not', 'through']),
    (15, ['the air', 'the family', 'the chicken', 'the cockroach', 'the buffalo', 'the chili pepper', 'the spoon', 'the butter', "the (woman's) dress", 'the stove', 'the bed', 'the room', 'the farmer', 'the bamboo', 'the axe/ax', 'the rug', 'the knife(2)', 'the basket', 'the hammer', 'cheap', 'the pair', 'the soul or spirit', 'the good luck', 'the king', 'the boundary', 'the sword', 'the demon', 'to bless', 'to brake']),
    (27, ['the lion', 'the tobacco', 'the paper']),
    (28, ['the match', 'the film/movie']),
    (35, ['the coffee']),
    (30, ['the car', 'the machine', 'the television']),
    (34, ['the motor']),
    (31, ['the hour', 'the telephone']),
]

concepts_in_impl = [
    (11, ['the he-goat']),
    (10, ['the west', 'nine', 'seven']),
    (9, ['the moon', 'twelve', 'eight', 'six', 'eleven', 'the month']),
    (8, ['the son-in-law (of a man)', 'the father-in-law (of a woman)', 'the tree', 'the east', 'three', 'the language']),
    (7, ['the ash', 'the bolt of lightning', 'the mother-in-law (of a woman)', 'the son-in-law (of a woman)', 'the kid', 'the hole', 'four', 'to whistle']),
    (6, ['the darkness', 'the star', 'the lightning', 'the wood', 'the daughter-in-law (of a man)', 'the daughter-in-law (of a woman)', 'the father-in-law (of a man)', 'the stepfather', 'the deer', 'male(2)', 'to sneeze', 'the leg', 'the claw', 'the toe', 'to lick', 'the supper', 'to swim', 'to pursue', 'to send', 'to limp', 'to destroy', 'high', 'fifteen', 'to cease', 'the spring(2)', 'brave', 'to guess', 'the stranger']),
    (5, ['the granddaughter', 'the grandson', 'male(1)', 'the stepdaughter', 'the finger', 'the hand', 'the ankle', 'the lip', 'the dinner', 'to sweep', 'to fly', 'to twist', 'to injure', 'deep', 'inside', 'tall', 'near', 'the autumn/fall', 'fragrant']),
    (4, ['the thunder', 'the woods or forest', 'the mother-in-law (of a man)', 'the stepson', 'the stepmother', 'female(2)', 'to die', 'dead', 'the neck', 'to conceive', 'the arm', 'the body hair', 'to peel', 'to bore', 'to lend', 'to borrow', 'to open', 'to separate', 'to cover', 'the corner', 'the remains', 'the middle', 'to hide', 'narrow', 'last', 'soon', 'again', 'to look', 'sharp', 'to smell(1)', 'good', 'to stutter or stammer', 'to hunt']),
    (3, ['to burn(1)', 'female(1)', 'the parents', 'mute', 'the foot', 'the fingernail', 'to sleep', 'to shiver', 'the gums', 'cooked', 'to suck', 'to make', 'to fold', 'to untie', 'to carry under the arm', 'to climb', 'to slide or slip', 'to let go', 'in', 'sometimes', 'quiet', 'how many?', 'how much?']),
]

list.sort(concepts_singletons, key=lambda x: x[0])
list.sort(concepts_in_impl, key=lambda x: x[0])

fig, ax = plt.subplots()
ax.set_xlabel('Number of languages that borrowed the same concept')
ax.set_ylabel('Number of concepts by number target languages')
line1, = ax.plot([key for (key, _) in concepts_singletons],
                 [len(val) for (_, val) in concepts_singletons],
                 color='tab:red', marker='x',
                 zorder=10)
line1.set_label('Concepts outside concept pairs with NPMI >= 0.7')
line2, = ax.plot([key for (key, _) in concepts_in_impl],
                 [len(val) for (_, val) in concepts_in_impl],
                 color='tab:blue', marker='o',
                 zorder=5)
line2.set_label('Concepts in concept pairs with NPMI >= 0.7')
# ax.tick_params(axis='y')
ax.set_xticks(range(3, 36, 2))
ax.set_xlim(2.5, 35.5)
ax.grid(zorder=0)
ax.legend()
fig.tight_layout()
# fig.savefig("out/singleton_vs_impl.png")
plt.show()
